### ISSUE TITLE
#QuickStart contracts are lost when resuming to the flight view

### ISSUE THREAD

**Issue by Gnurfos** [malahx/QuickMods#25]
(At least active contracts, but I think also completed ones).
This seems systematic on my install but I have many mods. The game was saved/quit using QuickExit, but selecting the KSC instead keeps the contracts.

**Comment by malahx** [comment]
Hello, it's a known bug, it's because you have too many mods, and the loading time becomes longer. It's why there's an option to add a waiting time on the scene switching, try to put this setting to 5 seconds on the QuickStart setting. If it correct your bug I will close this bug report, if not, can you send me your log?

**Comment by Gnurfos** [comment]
It seems I already have 5 seconds (isn't that the default ? I don't rember changing it).Couldn't something else than timer-based be done ? Maybe something that checks the game time, and only start doing things when it changes (supposing this means other mods have finished initializing their stuff) ?

**Comment by malahx** [comment]
I haven't found an other way to do it ...
(it's default to 5 seconds with Kopernicus)

**Comment by malahx** [comment]
Hello, if this bug occurs only when you start to the last flight I think the last commit corrects it. I haven't tried it with a highly modded install.

Can you try to replace the QuickStart dll with this one: https://github.com/malahx/QuickMods/raw/master/QuickStart/GameData/QuickMods/QuickStart/Plugins/QuickStart.dll ? (you need to replace the dll which is on GameData/QuickMods/QuickStart/Plugins). Thanks.
